- hosts: appservers-php
  sudo: yes
  gather_facts: False

  tasks:
        - name: Execute service action
          service:
                name: "{{ service_name }}"
                state: "{{ service_action }}"

#--extra-vars "service_action=restart service_name=mysql"
